### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by Tessaira** [Tessaira/Ballistic-iwag#2]
The Game is currently called BouncyBall and I want to rename it to Ballistic. However, I need to know all necessary steps in order to do so.

**Comment by smeerws** [comment]
going to github.com on your repository
Open Settings Tab
The first setting you can see is the "Repository Name"
Change the actual one and put the new name you want to give to your repository
Click on Rename
After this step, GitHub will make sure that, your online repository matches your local folder name. At this step your problem is solved, unless you also want to rename your local folder. Then do it manually and just use the Github client for windows to refind again your repository into your hard drive, and Github will match it again. That's all! Very simple.

https://stackoverflow.com/questions/5751585/how-do-i-rename-a-repository-on-github

**Comment by Tessaira** [comment]
Fixed! Thank you.
